spring:
  application:
    name: kmtech.api

  datasource:
    url: jdbc:postgresql://localhost:5433/kmtech_db
    username: postgres
    password: amir2026

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true